const ActionType = {
  GET_FILMS_REQUEST: "GET_FILMS_REQUEST",
  GET_FILM_SUCCESS: "GET_FILM_SUCCESS",
  GET_FILM_ERROR: "GET_FILM_ERROR",
  GET_MORE_FILM_REQUEST: "GET_MORE_FILM_REQUEST",
  GET_MORE_FILM_SUCCESS: "GET_MORE_FILM_SUCCESS",
  GET_TOTAL_FILMS_PAGES: "GET_TOTAL_FILMS_PAGES",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_SEARCH_STRING: "SET_SEARCH_STRING",
  GET_FILM_DETAILS_REQUEST: "GET_FILM_DETAILS_REQUEST",
  GET_FILM_DETAILS_SUCCESS: "GET_FILM_DETAILS_SUCCESS",
  GET_FILM_DETAILS_ERROR: "GET_FILM_DETAILS_ERROR",
};

export default ActionType;
