const ActionType = {
  GET_GENRES_REQUEST: "GET_GENRES_REQUEST",
  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_ERROR: "GET_GENRES_ERROR",
  CHANGE_ACTIVE_GENRE: "CHANGE_ACTIVE_GENRE",
};

export default ActionType;
